#!/usr/bin/env bash
# =============================================================================
# Orchestra MCP — Local Development Server
#
# Starts the Supabase stack locally for development.
# Uses docker-compose.local.yml override for localhost ports.
#
# Usage:
#   ./local.sh              # Start local dev server
#   ./local.sh --stop       # Stop all services
#   ./local.sh --reset      # Stop + delete all data (fresh start)
#   ./local.sh --logs       # Tail logs
#   ./local.sh --status     # Check service status
#   ./local.sh --studio     # Open Studio in browser
#   ./local.sh --psql       # Connect to PostgreSQL
# =============================================================================

set -euo pipefail
cd "$(dirname "$0")"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log()  { echo -e "${GREEN}[local]${NC} $*"; }
warn() { echo -e "${YELLOW}[local]${NC} $*"; }
err()  { echo -e "${RED}[local]${NC} $*" >&2; }

COMPOSE_FILES="-f docker-compose.yml -f docker-compose.local.yml"

# Check prerequisites
command -v docker >/dev/null 2>&1 || { err "docker is required but not installed."; exit 1; }
docker compose version >/dev/null 2>&1 || { err "docker compose v2 is required."; exit 1; }

# Auto-create .env from example if missing
setup_env() {
    if [ -f .env ]; then
        return 0
    fi

    log "No .env found. Generating local development environment..."

    local jwt_secret pg_pass realtime_secret secret_key vault_key realtime_db_key ch_pass dash_pass

    jwt_secret=$(openssl rand -hex 32)
    pg_pass=$(openssl rand -hex 16)
    realtime_secret=$(openssl rand -hex 64)
    secret_key=$(openssl rand -hex 32)
    vault_key=$(openssl rand -hex 16)
    realtime_db_key=$(openssl rand -hex 16)
    ch_pass=$(openssl rand -hex 8)
    dash_pass="localdev$(openssl rand -hex 4)"

    # Generate Supabase JWT keys
    local anon_key service_key
    if command -v python3 &>/dev/null; then
        python3 -c "import jwt" 2>/dev/null || pip3 install -q PyJWT 2>/dev/null || true
        anon_key=$(python3 -c "
import jwt
print(jwt.encode({'role':'anon','iss':'supabase','iat':1735689600,'exp':1893456000}, '$jwt_secret', algorithm='HS256'))
" 2>/dev/null || echo "GENERATE_ME")
        service_key=$(python3 -c "
import jwt
print(jwt.encode({'role':'service_role','iss':'supabase','iat':1735689600,'exp':1893456000}, '$jwt_secret', algorithm='HS256'))
" 2>/dev/null || echo "GENERATE_ME")
    else
        anon_key="GENERATE_ME"
        service_key="GENERATE_ME"
        warn "python3 not found — set ANON_KEY and SERVICE_ROLE_KEY manually in .env"
    fi

    # Generate Caddy password hashes
    local dash_hash ch_hash
    dash_hash=$(docker run --rm caddy:2.9-alpine caddy hash-password --plaintext "$dash_pass" 2>/dev/null || echo "GENERATE_ME")
    ch_hash=$(docker run --rm caddy:2.9-alpine caddy hash-password --plaintext "$ch_pass" 2>/dev/null || echo "GENERATE_ME")

    cat > .env <<EOF
# Orchestra MCP — Local Development Environment
# Auto-generated by local.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

POSTGRES_PASSWORD=${pg_pass}
POSTGRES_DB=postgres

JWT_SECRET=${jwt_secret}
JWT_EXPIRY=3600
ANON_KEY=${anon_key}
SERVICE_ROLE_KEY=${service_key}

GOTRUE_MAILER_AUTOCONFIRM=true
GOTRUE_SMS_AUTOCONFIRM=true
GOTRUE_DISABLE_SIGNUP=false
GOTRUE_URI_ALLOW_LIST=http://localhost:3000/**,http://localhost:54323/**

GITHUB_AUTH_ENABLED=false
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=

GOOGLE_AUTH_ENABLED=false
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_ADMIN_EMAIL=noreply@localhost
SMTP_SENDER_NAME=Orchestra MCP (Local)

REALTIME_DB_ENC_KEY=${realtime_db_key}
REALTIME_SECRET_KEY_BASE=${realtime_secret}

CF_API_TOKEN=not-needed-for-local

DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD=${dash_pass}
DASHBOARD_PASSWORD_HASH=${dash_hash}

CLICKHOUSE_USER=orchestra
CLICKHOUSE_PASSWORD=${ch_pass}
CLICKHOUSE_ADMIN_USER=admin
CLICKHOUSE_ADMIN_HASH=${ch_hash}

SECRET_KEY_BASE=${secret_key}
VAULT_ENC_KEY=${vault_key}
EOF

    chmod 600 .env
    log ".env created with auto-generated secrets."
    log "Studio login: supabase / ${dash_pass}"
}

# Create local override if missing
setup_local_compose() {
    if [ -f docker-compose.local.yml ]; then
        return 0
    fi

    log "Creating docker-compose.local.yml (localhost port mappings)..."

    cat > docker-compose.local.yml <<'EOF'
# =============================================================================
# Orchestra MCP — Local Development Overrides
#
# Exposes all services on localhost ports. No TLS, no Caddy.
# Used with: docker compose -f docker-compose.yml -f docker-compose.local.yml up -d
# =============================================================================

services:
  # Expose PostgreSQL on localhost:54322
  supabase-db:
    ports:
      - "54322:5432"

  # Expose Kong (API gateway) on localhost:54321
  supabase-kong:
    ports:
      - "54321:8000"
      - "54322:8443"

  # Expose GoTrue on localhost:54324
  supabase-auth:
    ports:
      - "54324:9999"

  # Expose Realtime on localhost:54325
  supabase-realtime:
    ports:
      - "54325:4000"

  # Expose Storage on localhost:54326
  supabase-storage:
    ports:
      - "54326:5000"

  # Expose Studio on localhost:54323
  supabase-studio:
    ports:
      - "54323:3000"

  # Expose Edge Runtime on localhost:54327
  supabase-edge:
    ports:
      - "54327:8081"

  # Expose ClickHouse on localhost:54328
  clickhouse:
    ports:
      - "54328:8123"
      - "54329:9000"

  # Expose Postgres Meta on localhost:54330
  supabase-meta:
    ports:
      - "54330:8080"

  # Disable Caddy in local mode (direct port access)
  caddy:
    profiles: ["production"]

  # Disable Gateway in local mode (built separately)
  gateway:
    profiles: ["production"]

  # Disable Next.js in local mode (run via next dev)
  nextjs:
    profiles: ["production"]
EOF

    log "docker-compose.local.yml created."
}

case "${1:-}" in
    --stop)
        log "Stopping local dev server..."
        docker compose $COMPOSE_FILES down
        log "Stopped."
        ;;
    --reset)
        warn "Stopping and deleting ALL local data (volumes)..."
        echo -n "Are you sure? [y/N]: "
        read -r confirm
        if [[ "$confirm" =~ ^[Yy] ]]; then
            docker compose $COMPOSE_FILES down -v
            rm -f .env docker-compose.local.yml
            log "Reset complete. Run ./local.sh to start fresh."
        else
            log "Cancelled."
        fi
        ;;
    --logs)
        docker compose $COMPOSE_FILES logs -f --tail=100
        ;;
    --status)
        docker compose $COMPOSE_FILES ps
        ;;
    --studio)
        log "Opening Studio at http://localhost:54323"
        if command -v open &>/dev/null; then
            open "http://localhost:54323"
        elif command -v xdg-open &>/dev/null; then
            xdg-open "http://localhost:54323"
        else
            log "Open http://localhost:54323 in your browser"
        fi
        ;;
    --psql)
        log "Connecting to PostgreSQL..."
        docker compose $COMPOSE_FILES exec supabase-db psql -U postgres
        ;;
    --help|-h)
        echo ""
        echo -e "${BOLD}Orchestra MCP — Local Development Server${NC}"
        echo ""
        echo "Usage: ./local.sh [command]"
        echo ""
        echo "Commands:"
        echo "  (none)      Start local dev server"
        echo "  --stop      Stop all services"
        echo "  --reset     Stop + delete all data (fresh start)"
        echo "  --logs      Tail service logs"
        echo "  --status    Check service status"
        echo "  --studio    Open Studio in browser"
        echo "  --psql      Connect to PostgreSQL"
        echo ""
        echo "Local ports:"
        echo "  54321  Kong (API gateway)"
        echo "  54322  PostgreSQL"
        echo "  54323  Studio (dashboard)"
        echo "  54324  GoTrue (auth)"
        echo "  54325  Realtime"
        echo "  54326  Storage"
        echo "  54327  Edge Runtime"
        echo "  54328  ClickHouse HTTP"
        echo "  54330  Postgres Meta"
        echo ""
        ;;
    *)
        setup_env
        setup_local_compose

        log "Starting local dev server..."
        docker compose $COMPOSE_FILES up -d

        log "Waiting for services..."
        sleep 5

        docker compose $COMPOSE_FILES ps

        echo ""
        echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
        echo -e "${BOLD}  Orchestra MCP — Local Dev Server Running${NC}"
        echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
        echo ""
        log "Services:"
        log "  Studio:     http://localhost:54323"
        log "  Kong API:   http://localhost:54321"
        log "  PostgreSQL: localhost:54322 (user: postgres)"
        log "  Auth:       http://localhost:54324"
        log "  Realtime:   http://localhost:54325"
        log "  Storage:    http://localhost:54326"
        log "  Edge:       http://localhost:54327"
        log "  ClickHouse: http://localhost:54328"
        echo ""
        log "Studio login: supabase / (see .env for DASHBOARD_PASSWORD)"
        echo ""
        log "Manage:"
        log "  ./local.sh --logs     # View logs"
        log "  ./local.sh --status   # Check status"
        log "  ./local.sh --studio   # Open Studio in browser"
        log "  ./local.sh --psql     # PostgreSQL shell"
        log "  ./local.sh --stop     # Stop everything"
        log "  ./local.sh --reset    # Delete all data + start fresh"
        echo ""
        warn "Caddy, Gateway, and Next.js are disabled in local mode."
        warn "Run Next.js separately: cd apps/next && npm run dev"
        warn "Run Gateway separately: cd apps/gateway && go run ."
        ;;
esac
